- .pre-commit-config.yaml
- pyglotaran_extras/io/load_data.py
- pyglotaran_extras/plotting/plot_doas.py
- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_residual.py
- pyglotaran_extras/plotting/plot_spectra.py
- pyglotaran_extras/plotting/plot_svd.py
- pyglotaran_extras/plotting/plot_traces.py
- setup.py
Removing the calls to `plt.draw()` makes plots work properly in notebooks.
Tested in:
- Notebooks
- Scripts
- VS-Code interactive mode
The downside is that you won't see anything happening till all plots are done.
But since this PR removes the calls to `plt.pause(0.001)` and `plt.draw()` ([which redraws the whole figure](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.draw.html)) the plots in general is faster.
> ✨Make plotting compatible with Jupyter notebooks

- tests/io/test_boilerplate.py
Yeah, should have tested it on WSL2 before ... kinda annoying that when using `shell=True` you need to differentiate between OS but oh well.
This time I tested it on:
- WSL2
- git bash
- conda cmd
- Changed subprocess call to use `str` instead of `list`
> 🩹 Fix tests on none windows platform

- setup.cfg
The upper pyglotaran limit causes the `pyglotaran/examples` action to uninstall the current pyglotaran version and use an old one. This leads to false-positive tests.
Also the upper limit isn't needed anymore since pyglotaran now uses a proper deprecation system.
- Removed upper pyglotaran limit for the package
> 🩹 Remove upper pyglotaran version limit

- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_traces.py
This change prevents crashes when using results from `pyglotaran==0.5.0-dev` in cases where the `irf` has multiple centers and dispersion.
It also adds forward compatibility to the name change `center_dispersion_1` -> `irf_center_location`.
The assumption to use `irf_loc = irf_loc.mean()` is, that the center locations of the `irf` only disperse over the spectral dimension and not over `time`.
- Allows usage with multidimensional `irf_loc` (`spectral`, `irf_nr`)
> ✨Compatibility to pyglotaran (0.5.0-dev) staging branch

- pyglotaran_extras/plotting/plot_traces.py
Follow up PR for #30
Since the [DPSI case study](https://github.com/s-weigand/pyglotaran-examples/blob/notebooks/notebooks/DPSI/DPSI_case_study.ipynb) was broken until https://github.com/glotaran/pyglotaran/pull/797 we didn't see that the plottings breaks.
I tested it against all the notebooks on my notebook branch and examples on `pyglotaran-examples` main branch.
- Fix irf location selection for irfs with multiple components
> 🩹 Fix irf location selection for irfs with multiple components

- pyglotaran_extras/io/__init__.py
This will make it easier to rename the boilerplate module (#17 )
- Shorter import of `setup_case_study` (`from pyglotaran_extras.io import setup_case_study`)
> ♻️ Export 'setup_case_study' from 'pyglotaran_extras.io'

- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/plot_svd.py
- setup.cfg
Handle missing SVD by computing them if they are missing in plots that use them.
We still need to add some unit testing for this, but first we need to have a look at how to properly test plots 😅
- 👌 Handle missing SVD by computing them if missing in plots that use them
- 🚧 Disallow `xarray` versions breaking plotting in integration tests(See also https://github.com/glotaran/pyglotaran/pull/900)
closes #16
> 🩹 Handle missing SVD attributes

- README.md
Since the readme will be shown on PyPi we should also mention how to install it from there (@jsnel good catch thanks)
- [📚 Updated installation instruction for release on pipi](https://github.com/glotaran/pyglotaran-extras/commit/4ad49d9cfe91cc9a63ece4cb6bbb1c73619f0acd)
> 📚 Update installation instruction for release on pipi

- .github/workflows/integration-tests.yml
- .github/workflows/test.yml
Looks like specifying `branches-ignore` on the push event also prevents it from running on pushed tags.
This prevents the release workflow from publishing to PyPI.
- [🩹🚇 Fixed release pipeline not running on push tag](https://github.com/glotaran/pyglotaran-extras/commit/4c52b7071ca6dcaab5103b4033708fd7bc47a6b7)
> 🩹🚇 Fix release pipeline not running on push tag

- pyglotaran_extras/plotting/plot_concentrations.py
- pyglotaran_extras/plotting/plot_doas.py
- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_residual.py
- pyglotaran_extras/plotting/plot_spectra.py
- pyglotaran_extras/plotting/plot_svd.py
- pyglotaran_extras/plotting/plot_traces.py
- pyglotaran_extras/plotting/utils.py
- tests/plotting/__init__.py
- tests/plotting/test_utils.py
This change is needed in order to reuse plot functions in loops where the cycler is controlled from the outside.
- [👌 Made adding a cylcer to and axis opt out by using None](https://github.com/glotaran/pyglotaran-extras/commit/560175c696083506a54435bb67af6a805af0cf7d)
> 👌 Made adding a cycler to and axis opt out by using None

- pyglotaran_extras/plotting/plot_concentrations.py
Since we don't set the title for concentration plots they are left with the autogenerated ones by xarray.
Before:
After:
- [🩹 Fixed autogenerated title for concentration plot](https://github.com/glotaran/pyglotaran-extras/commit/c2d089d6ec7393fea6658da7ae7e3d88dfe0419a)
<!-- Links to the changed sections
- [🩹 Fixed autogenerated title for concentration plot](https://github.com/glotaran/pyglotaran-extras/commit/c2d089d6ec7393fea6658da7ae7e3d88dfe0419a)
> 🩹 Fix autogenerated title for concentration plot

- .sourcery.yaml
Looks like sourcery AI won't refactor branches when the github section is in the config.
My guess is that `sourcery_branch: sourcery/{base_branch}` isn't handled gracefully, when not triggered by a webhook (`KeyError` ?).
- [🩹 Remove github section in sourcery config due to bug in sourcery-ai](https://github.com/glotaran/pyglotaran-extras/commit/362b2259505cbc45431b3918c95860a6023575b4)
> 🔧🩹 Remove github section in sourcery config due to bug in sourcery-ai

- pyglotaran_extras/plotting/plot_data.py
Just some minor improvements on pacing legends for `plot_data_overview`
Legend hides part of the plot and has redundant information since the legends for LSV and RSV link the same color to the same index.
When users want to plot more vectors things get out of control
Also plays nicely if users want to plot more vectors
> 👌 Improve legend placement in plot_data_overview

- .github/workflows/integration-tests.yml
- .github/workflows/test.yml
Since bots push to the repo and create PRs there is no need to also check their pushes, the PRevent is enougth.
- [🚇👌 Exclude pre-commit and sourcery branches from CI push run](https://github.com/glotaran/pyglotaran-extras/commit/d5189f345373d484220871d50f117088f8553c4a)
> 🚇👌 Exclude pre-commit and sourcery branches from CI push run

- .github/workflows/integration-tests.yml
This way the integration tests will manage the list of examples that will be run by themselves and won't forget any.
- [👌🚇 Change integration tests to use self managed examples action](https://github.com/glotaran/pyglotaran-extras/commit/506ccc5db83ec3aa841066b33c1f1e19a5e92001)
> 👌🚇 Change integration tests to use self managed examples action

- pyglotaran_extras/__init__.py
- pyglotaran_extras/plotting/plot_guidance.py
- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_traces.py
This PR adds a new plot function for guidance spectra and prevents `plot_overview` from raising an exception when provided with guidance spectra data, by checking the dimensionality of the time coordinate and using `plot_guidance` if only a single time point is present.
- [👌 Prevent crash of plot_fitted_traces when guidence spectrum in result](https://github.com/glotaran/pyglotaran-extras/commit/a42a863d6751cfa1d832b4eefc9f74370872f761)
- [✨ Added 'plot_guidance' function](https://github.com/glotaran/pyglotaran-extras/commit/3af189f95f1ca1c4e333a4248aa304d435950b45)
- [👌 Fall back to plot_guidance in plot_overview for guidance spectrum](https://github.com/glotaran/pyglotaran-extras/commit/49fdc4b206192e8d304361d1d08dd197e779969e)
- [🩹 Respect figure_only argument for guidance case in …
> ✨ Add plot function for guidance spectra

- pyglotaran_extras/plotting/plot_svd.py
Just fixed a typo (introduced by me) that bugged me 😅
- [👌 Fixed typo in internal function name](https://github.com/glotaran/pyglotaran-extras/commit/cb3c7438a00d0bd221e8dcf5278107a19b2268bc)
> 👌 Fix typo in internal function name

- codecov.yml
Just a basic config so codecov won't annoy us with meaningless failed patch checks all the time.
- [🔧 Add basic codecov config](https://github.com/glotaran/pyglotaran-extras/commit/ab7cbaf2b83492415873bf39b4ead1f49376078e)
> 🔧 Add basic codecov config

- .pre-commit-config.yaml
- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/plot_irf_dispersion_center.py
- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_residual.py
- pyglotaran_extras/plotting/plot_svd.py
- pyglotaran_extras/plotting/utils.py
Since the time axis of the concentration plot is shifted so the location of the IRF is at 0 in overview plots, this makes it harder to compare it the residual/data and LSV plots, especially when using `linlog` axes.
This PR adds the argument `irf_location` to the low level plotting functions which shifts the time axis for those plots the same way the time axis of concentrations is shifted. This shift is automatically applied in `plot_overview` and `plot_simple_overview`.
It also allows for shifting the time axis for the `plot_data_overview` function, which will make it easier to "guesstimate" the initial center location of the IRF, especially when used together with `linlog` scaling.
- [♻️ Factored out time shifting by irf location into seperate …
> 👌 Shift time axis by IRF location

- README.md
Specifying the channel flag allows installation with conda even if users don't hate `conda-forge` added to their channels.
- [🩹📚 Fix missing channel flag in conda install guide](https://github.com/glotaran/pyglotaran-extras/commit/465fc57698ba8553574dfde750438da90e8ede06)
closes #105
> 🩹📚 Fix missing channel flag in conda install guide

- .github/workflows/test.yml
- changelog.md
- readthedocs.yml
Currently the CI step `Test pyglotaran dev` [is failing](https://github.com/glotaran/pyglotaran-extras/actions/runs/3570554513/jobs/6001697589) because the development version of pyglotaran on main requires python `3.10` and the step is configured to use python `3.8`. In addition, I also added python `3.10` as a version in the CI test matrix and changed the RTD config to build docs on python `3.10`.
- [🩹🚇 Raised python version for glotaran-dev test to 3.10](https://github.com/glotaran/pyglotaran-extras/commit/ab8913abeb6d5cb37d21cf3f3d0c0a77cb7769fd)
- [🚇👌 Added python 3.10 to python versions for unit tests](https://github.com/glotaran/pyglotaran-extras/commit/c2b416a900b5e0f158d6f1ac78c6bc31f2841639)
- [🚇📚 Upgraded readthedocs.yml so RTD builds on python …
> 🩹🚇 Fix 'Test pyglotaran dev' CI step

- changelog.md
- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_residual.py
Especially for big datasets the 2D plots (data/residual) in `plot_overview` or `plot_simple_overview` can take a long time (up to 1 minute). This change adds `None` as a possible value for `show_data` which allows switching off this part of the plot altogether, instead "Skipped" will be written to the middle of the axis (subplot).
The following code will generate the plot below it
```python
from glotaran.testing.simulated_data.sequential_spectral_decay import SCHEME
from glotaran.optimization.optimize import optimize
from pyglotaran_extras import plot_overview
result = optimize(SCHEME)
plot_overview(
result.data["dataset_1"],
figure_only=False,
nr_of_data_svd_vectors=3,
nr_of_residual_svd_vectors=1,
show_data=None,
linlog=True,
linthresh=50,
)
```
- [👌 Added option to deactivate 2D …
> 👌 Add option to deactivate data/residual plotting in overview plots

- pyglotaran_extras/__init__.py
- pyglotaran_extras/plotting/plot_coherent_artifact.py
- pyglotaran_extras/plotting/utils.py
- tests/plotting/test_utils.py
This change adds a new plot function `plot_coherent_artifact` which implements #33.
Here are some example plots for the [DOAS example](https://github.com/glotaran/pyglotaran-examples/tree/main/pyglotaran_examples/ex_doas_beta) (currently our only example that uses the coherent artifact):
- :sparkles: [ Added abs_max helper function](https://github.com/glotaran/pyglotaran-extras/commit/de7bd7a0051c62c0bd4d12d8e20db1720ffba7b8)
- :recycle: [ Refactored add_cycler_if_not_none to also work on multiple axes](https://github.com/glotaran/pyglotaran-extras/commit/f38fbf855c62612dfcd8bfe7d9a2c4b1a1b2af04)
- :sparkles: [ Added plot_coherent_artifact function](https://github.com/glotaran/pyglotaran-extras/commit/9631fa17f028c340b8f448f9d855d10fd5aaae85)
Not sure for which other plots #33 applies, so …
> ✨ Add coherent artifact plot functionality

- .pre-commit-config.yaml
- pyglotaran_extras/inspect/__init__.py
- pyglotaran_extras/inspect/a_matrix.py
- pyglotaran_extras/inspect/utils.py
- requirements_dev.txt
- setup.cfg
- tests/__init__.py
- tests/conftest.py
- tests/data/a_matrix/a_matrix_to_html_table_decimal_2.md
- tests/data/a_matrix/a_matrix_to_html_table_default.md
- tests/data/a_matrix/a_matrix_to_html_table_normalized.md
- tests/data/a_matrix/show_a_matrixes_decimal_2.md
- tests/data/a_matrix/show_a_matrixes_default.md
- tests/data/a_matrix/show_a_matrixes_expanded_dataset_2.md
- tests/data/a_matrix/show_a_matrixes_heading_offset_0.md
- tests/data/a_matrix/show_a_matrixes_min_size_2.md
- tests/data/a_matrix/show_a_matrixes_normalized.md
- tests/inspect/__init__.py
- tests/inspect/test_a_matrix.py
- tests/inspect/test_utils.py
This change adds a new sub package for inspection functions (`pyglotaran_extras.inspect`) and the `show_a_matrixes` function to render all a-matrixes in a `ResultLike` optimization result.
The rendered matrixes are wrapped in a html details tag per dataset, which is collapsed by default.
Inside the details tag, the matrixes are placed under a heading with the corresponding megacomplex name.
Here is an example of what output looks like, for more examples have a look at the markdown preview of the [added unit test data](https://github.com/s-weigand/pyglotaran-extras/tree/show-a-matrix/tests/data/a_matrix):
- :sparkles: [ Added wrap_in_details_tag utility function](https://github.com/glotaran/pyglotaran-extras/commit/b8a3b6f6da3309ed2c30c6dac5025a805bdf49bf)
- :construction: [ Made implicit …
> ✨ Add a-matrix inspection function

- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_spectra.py
- pyglotaran_extras/plotting/plot_traces.py
This change adds the option `show_zero_line` to `plot_fitted_traces` (applied to all axes) and `plot_overview` (only applied to spectra SAS/DAS). The zero lines are added by default since it falls more in line with plots by @ism200 which makes comparing plots to former publications easier. 
- [:sparkles: Added show_zero_line arg to plot_overview and plot_fitted_traces](https://github.com/glotaran/pyglotaran-extras/commit/3f9c3a9971039b9a88cf29e614e3a51b66705f73)
> ✨ Add show_zero_line option to plot_overview and plot_fitted_traces

- pyglotaran_extras/plotting/plot_svd.py
Since we mostly plot the first SVD vectors starting from zero we didn't see this bug yet.
But when you use different indices (e.g. to plot a specific vector) the legend still uses a range starting at zero.
```python
import matplotlib.pyplot as plt
from pyglotaran_extras.plotting.plot_svd import plot_lsv_residual
fig, axes = plt.subplots(1, 2, figsize=(20, 5))
plot_lsv_residual(result.data["dataset1"],axes[0], indices=[0])
plot_lsv_residual(result.data["dataset1"],axes[1], indices=[1])
```
- [🩹 Fix SVD vector labels always starting from zero](https://github.com/glotaran/pyglotaran-extras/commit/2937cecbd15c66fdf2ccdbebb7d405646ea1fd84)
> 🩹 Fix SVD vector labels always starting from zero

- .pre-commit-config.yaml
- pyglotaran_extras/io/load_data.py
- pyglotaran_extras/plotting/plot_coherent_artifact.py
- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/plot_guidance.py
- pyglotaran_extras/plotting/plot_overview.py
- tests/conftest.py
- tests/io/test_load_data.py
This PR allows the passing of `Result` and file paths as input to `plot_coherent_artifact` in addition users now get a warning when passing a `Result` with multiple datasets to the high level plot functions where `load_data` picks the first dataset for user convenience and to prevent crashes.
- [👌 Made result input for plot_coherent_artifact more generic](https://github.com/glotaran/pyglotaran-extras/commit/67b1d1df357b9b708ce3c42d60e0d73f76de71ba)
- [👌 Warn when picking a single dataset from a result with multiple datasets](https://github.com/glotaran/pyglotaran-extras/commit/d5f4ada001d5d396adeb1e804605460d754d9a04)
> 👌 Make result input for plot_coherent_artifact more generic

- pyglotaran_extras/__init__.py
- pyglotaran_extras/plotting/plot_doas.py
- pyglotaran_extras/plotting/utils.py
- tests/plotting/test_utils.py
This PR replaces the current `plot_doas`  function which was meant as an augmented ``plot_overview`` and is broken on `main` with a more focused (3 plots) version that only plots DOAS-related information.
In addition, it adds a custom plot tick calculation function for values that are in the unit of Pi.
**Note:** The slight variations are due to a slightly different model using DOAS to fit parts of the coherent artifact for better fit results and the flipped phase for `osc1` is due to using `np.unwrap` in pyglotaran in contrast to `mod 2*Pi` in the original plot
As for adding `\overline{\nu}...` as text labels to the plots this should be done via a helper function since it would need a latex environment at the user side installed, which we should not force on them to have by default. …
> ✨ Add plot_doas function that only plots DOAS related information

- pyglotaran_extras/plotting/plot_coherent_artifact.py
This PR adds `main_irf_nr` to `plot_coherent_artifact` which defaults to 0 and shifts the IRF derivatives to by the position of the IRF component with index 0. If `main_irf_nr` is set to `None` the IRF shifting is deactivated.
- [✨ Shift irf derivatives in plot_coherent_artifact by irf position](https://github.com/glotaran/pyglotaran-extras/commit/f5aafe6d5ec954db6e921c126dba46872623c438)
> ✨ Shift irf derivatives in plot_coherent_artifact by irf position

- pyglotaran_extras/plotting/style.py
This allows using the enums directly without using the value property.
Before
```py
from pyglotaran_extras.plotting.style import ColorCode
green = ColorCode.green.value
```
After
```py
from pyglotaran_extras.plotting.style import ColorCode
green = ColorCode.green
```
- [👌 Convert plot style Enums to StrEnums for ease of use](https://github.com/glotaran/pyglotaran-extras/commit/2b270977b925250ce56090dca89ea8772ad3bedd)
> 👌 Convert plot style Enums to StrEnums for ease of use

- pyglotaran_extras/inspect/a_matrix.py
- tests/data/a_matrix/show_a_matrixes_multiple_a_matrixes_in_dataset.md
- tests/inspect/test_a_matrix.py
Just 2 additional new lines in front of the heading above the table (megacomplex name), so it renders as heading.
- [🩹 Fixed missing new lines in front of megacomplex heading](https://github.com/glotaran/pyglotaran-extras/commit/18dd39426139892e468f1ae8961daccd8f84818f)
> 🩹 Fix heading in show_a_matrixes for multiple a-matrixes per dataset

- pyglotaran_extras/plotting/plot_doas.py
This change adds a new argument to `legend_format_string` that allows defining a formatting rule for the legend as a format string and inset values for `label`, `frequency` and `rate`.
The default value is `"{label}: v={frequency:.0f}, Γ={rate:.1f}"`
Example plot from the [ex_doas_beta case study](https://github.com/glotaran/pyglotaran-examples/tree/main/pyglotaran_examples/ex_doas_beta)
<details>
<summary>
Plot code
</summary>
```py
from pyglotaran_extras import plot_doas
plot_doas(
result,
damped_oscillation=["osc1", "osc2", "osc3"],
time_range=(-0.1, 0.8),
);
```
</details>
- [👌 Added legend_format_string argument to plot_doas](https://github.com/glotaran/pyglotaran-extras/commit/c91cc69c87760cbe6e6a86ea48a3cb0f7347033a)
> 👌 Add legend_format_string argument to plot_doas

- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/utils.py
- tests/plotting/test_utils.py
This change allows `plot_data_overview` to be able to plot single trace data without crashing on a single axis dataset.
The SVD part of the plot will be skipped since it does not make sense.
Pseudo code to try it our:
```python
from glotaran.io import load_result
from pyglotaran_extras import plot_data_overview
result = load_result("my_result/result.yaml")
plot_data_overview(result.data['dataset1'].sel(spectral=0,method="nearest"))
```
- [✨ Implemented not_single_element_dims util function](https://github.com/glotaran/pyglotaran-extras/commit/32ce905ce4e0bca4c53c25ae2223ceac3a002485)
- [👌 Made plot_data_overview able to plot single trace data](https://github.com/glotaran/pyglotaran-extras/commit/17248849993759a3e11bb48a4eaf2b1dd5409957)
> 👌 Make plot_data_overview able to plot single trace data

- pyglotaran_extras/plotting/plot_coherent_artifact.py
- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/plot_doas.py
- pyglotaran_extras/plotting/plot_guidance.py
- pyglotaran_extras/plotting/plot_irf_dispersion_center.py
- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_traces.py
Just a minor fix for the typing of the `figsize` argument which currently is `tuple[int, int]` but should be `tuple[float, float]`.
See [matplotlib docs](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.figure.html)
- [🩹⌨️ Fix figsize typing](https://github.com/glotaran/pyglotaran-extras/commit/3d2eb2b1a319dba6d038082ec1462a5333a154e3)
> 🩹⌨️ Fix figsize typing

- changelog.md
- docs/conf.py
- docs/requirements.txt
Currently, the search functionality in our docs hangs indefinitely.
The error you get in the dev tools console is 
```js
Uncaught ReferenceError: jQuery is not defined
```
This relates to a change in the rtd theme and how to use it (old config).
- [🩹📚 Fix search in docs](https://github.com/glotaran/pyglotaran-extras/commit/0b991d721c114af42fd98ca6b6feb054682186dc)
> 🩹📚 Fix search in docs

- README.md
- setup.cfg
Just a small fix in the readme we saw we needed after the 0.7.0 release 😅
- [📚 Update readme](https://github.com/glotaran/pyglotaran-extras/commit/c1866023132ba2cebacd930c1f95e7a2ccaa7e87)
- [👌 Change development status from alpha to beta](https://github.com/glotaran/pyglotaran-extras/commit/eb9a9cef2a307626f346364f6ee61ed74f52c359)
> ⬆️📚 Update readme

- changelog.md
- pyglotaran_extras/plotting/plot_coherent_artifact.py
- pyglotaran_extras/plotting/plot_doas.py
This fixes crashes of `plot_doas` and `plot_coherent_artifact` where an IRF without dispersion is used which omits the spectral dimension in the result data.
- [🩹 Added check that spectral coord exists on data before selecting](https://github.com/glotaran/pyglotaran-extras/commit/8c6d7c6fd76c4f882fbfa0e1b9c49c70a8b600c8)
> 🩹 Fix crashes of plot_doas and plot_coherent_artifact for non dispersive IRF

- changelog.md
- setup.cfg
The upper python version limit will be determined by our dependencies (i.e. `pyglotaran`) so there is no need for us to set it.
This will allow us to raise the upper python version limit of `pyglotaran` without a new release of the extras and removes a kind of racing condition with the upper bounds.
- [🚧📦 Remove upper python version limit](https://github.com/glotaran/pyglotaran-extras/commit/9fb15ebaa2a9ef367c679fb19d459874ddcb5d7a)
> 🚧📦 Remove upper python version limit

- changelog.md
- pyglotaran_extras/plotting/plot_concentrations.py
- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/plot_residual.py
- pyglotaran_extras/plotting/plot_svd.py
- pyglotaran_extras/plotting/plot_traces.py
- pyglotaran_extras/plotting/utils.py
This change adds minor ticks to linlog plots which makes it easier to differentiate between the linear and logarithmic parts.
- [👌 Add minor ticks to linlog plots](https://github.com/glotaran/pyglotaran-extras/commit/686a9555703aabb7a1bc04e8667be173128359a6)
> 👌 Add minor ticks to linlog plots

- changelog.md
- pyglotaran_extras/plotting/plot_coherent_artifact.py
This fixes crashes `plot_coherent_artifact` where an IRF without dispersion is used which omits the spectral dimension in the result data.
- [🩹](https://github.com/glotaran/pyglotaran-extras/commit/53bbfb282fb175a038cd973ac80be686a2b22a6a) [Follow up fix for](https://github.com/glotaran/pyglotaran-extras/commit/53bbfb282fb175a038cd973ac80be686a2b22a6a) https://github.com/glotaran/pyglotaran-extras/pull/173
> 🩹 Fix crashes `plot_coherent_artifact` with none dispersive IRF

- changelog.md
- pyglotaran_extras/__init__.py
- pyglotaran_extras/plotting/utils.py
- pyglotaran_extras/types.py
- tests/plotting/test_utils.py
This adds `add_subplot_labels ` as a convenience function to add subplot labels.
Instead of duplicating code for each axis possibly creating inconsistency.
```py
axes[0].annotate("A", xy=(0.01, 0.89), xycoords="axes fraction", fontsize=16)
axes[1].annotate("B", xy=(0.01, 0.89), xycoords="axes fraction", fontsize=16)
axes[2].annotate("C", xy=(0.01, 0.89), xycoords="axes fraction", fontsize=16)
```
This function allows adding labels consistently for all axes
```py
add_subplot_labels(axes, label_position=(0.01, 0.89), label_format_function="upper_case_letter")
```
- [✨ Added format_sub_plot_number_upper_case_letter function](https://github.com/glotaran/pyglotaran-extras/commit/46e826d9c230b5ccb71004bfaf77797b96968bf1)
- [🩹📚 Fixed missing arg docstring for …
> ✨ Add add_subplot_labels function

- .github/workflows/integration-tests.yml
- .github/workflows/test.yml
- README.md
- binder/environment.yml
- changelog.md
- pyglotaran_extras/__init__.py
- setup.cfg
After the `0.7.1` release we can go back to the `0.8.0` development
- Update minimum Python version from 3.8 to 3.10
- [🚧 Back to 0.8.0 development](https://github.com/glotaran/pyglotaran-extras/commit/321250e40bd418320dd44584a0d53fd89a803998)
> 🚧 Back to 0.8.0 development

- pyglotaran_extras/plotting/plot_coherent_artifact.py
- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/plot_doas.py
- pyglotaran_extras/plotting/plot_residual.py
- pyglotaran_extras/plotting/plot_svd.py
- pyglotaran_extras/plotting/utils.py
This change fixes that high-level plot functions crash if the result data do not have a `time` axis (e.g. for a spectral model) and should be fully backwards compatible.
This is just a hotfix since it does not implement fully correct behavior for results from a spectral models (e.g. which plot to apply `linlog` to).
But properly handling non kinetic models will be left for a follow up PR.
- [🩹 Fix crash when plotting spectral model result](https://github.com/glotaran/pyglotaran-extras/commit/f4ea1577e6ddd96c9e38d75107e26869344a01b2)
> 🩹 Fix crash when plotting spectral model result

- .pre-commit-config.yaml
[See latest black release](https://github.com/psf/black/releases/tag/23.9.0)
> Black now has an
[official pre-commit mirror](https://github.com/psf/black-pre-commit-mirror). Swapping
https://github.com/psf/black to https://github.com/psf/black-pre-commit-mirror in
your .pre-commit-config.yaml will make Black about 2x faster (https://github.com/psf/black/pull/3828)
- [🧰 Use black-pre-commit-mirror for 2x speedup](https://github.com/glotaran/pyglotaran-extras/commit/03efc26c392b761e2955b5d4a62f4c8896a16a92)
> 🧰 Use black-pre-commit-mirror for 2x speedup

- pyglotaran_extras/plotting/plot_guidance.py
- pyglotaran_extras/plotting/plot_residual.py
If the weighted residual is present in the result we should show it instead of the unweighted residual.
- [if weighted_residual then plot it](https://github.com/glotaran/pyglotaran-extras/commit/67cec7c163489ed34c3b7840c5f31b482b02df68)
- [👌 Also use weighted_residual in plot_guidance if present](https://github.com/glotaran/pyglotaran-extras/commit/a1a699d8dec94e9c5b169c2f3eda3f0b3cb3e1df)
> 👌 Use weighted residual instead of residual plots if present

- pyglotaran_extras/plotting/plot_data.py
This change adds the ability to set the colormap and its range in `plot_data_overview`.
- 👌 Add colormap related arguments `cmap`, `vmin` and `vmax` to `plot_data_overview` to pass down to plot method ([See Also](https://docs.xarray.dev/en/latest/generated/xarray.plot.pcolormesh.html#xarray.plot.pcolormesh))
> 👌 Add color map arguments to plot_data_overview

- changelog.md
- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_spectra.py
- pyglotaran_extras/plotting/plot_svd.py
- pyglotaran_extras/types.py
This change allows setting a different cycler for `DAS` and `SVD` plots.
I introduced an `Unset` singleton (similar to `pydantics` `Undefined`) in order to allow this change without regressing current behavior.
I also deprecated the `cycler` argument to `plot_sv_data` and `plot_sv_residual` since it doesn't have an effect since there is only a single scatter lines plot where the style is overwritten in the plot method call.
- [👌 Add das_cycler and svd_cycler to plot collection functions](https://github.com/glotaran/pyglotaran-extras/commit/e7756c4637fe01d6b96a9a3d67c0e00d4473e805)
- [🗑️ Deprecate cycler argument in plot_sv_data and plot_sv_residual](https://github.com/glotaran/pyglotaran-extras/commit/f1f3f657332bdd942b83974ee88a6d3597568ddf)
> 👌 Add das_cycler and svd_cycler to plot collection functions

- pyglotaran_extras/plotting/plot_data.py
- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/plot_svd.py
This change adds the switch `use_svd_number` to SVD related plot functions and plot collection functions that use them. The default is `False` not cause regressions.
When set to `True` it adds a new coordinate `singular value number` (`singular_value_index +1`) and changes the labels from `singular_value_index` to `singular value number` (legend or x axis label).
I intentionally choose `singular value number` instead of `singular_value_number` since:
- It looks nicer
- It is created on a copy of the data and not accessible in the data that are being plotted
Note that I also changed the legend title in `plot_data_overview` from `"singular value index"` to `"singular_value_index"` for the `use_svd_number=False` case to be consistent with "can I access it on the data?" reasoning.
- [👌 Add …
> 👌 Add use_svd_number switch to use SV number instead of index as label

- changelog.md
- pyglotaran_extras/plotting/plot_data.py
This fixes an oversight in #219 where the `use_svd_number` argument wasn't passed long to `plot_sv_data` in `plot_data_overview` leading to inconsistent usage of svd number (starts at 1) and index (starts at 0)
- [🩹 Fix use_svd_number not being passed on to plot_sv_data in plot_data_overview](https://github.com/glotaran/pyglotaran-extras/commit/932e2717c2a86fc3af9c8a4f84dccfafbb5297fe)
> 🩹 Fix `use_svd_number` not being passed on to `plot_sv_data` in `plot_data_overview`

- .github/workflows/test.yml
- changelog.md
Using [trusted publishing](https://docs.pypi.org/trusted-publishers/) is the new recommended way to publish packages on PyPI by PyPI and [pypa/gh-action-pypi-publish](https://github.com/pypa/gh-action-pypi-publish/tree/v1.8.10/#trusted-publishing)
- [📦 Use trusted publisher workflow for publishing to pypi](https://github.com/glotaran/pyglotaran-extras/commit/c34d59839a221a80e2ce5ddaef91249f61da4444)
> 📦 Use trusted publisher workflow for publishing to PyPI

- pyglotaran_extras/plotting/plot_residual.py
This reduces plot time of `plot_residual` (also used inside of `plot_overview`) from 3min to 3sec.
By default `matplotlib` tries to find the ideal position to place the legend where it least interferes with the plot itself, but since we add the line plot of the IRF on top of a 2D plot of the data or residual this wastes a lot of time without getting a conclusive result.
- [🩹 Hard code legend position in 2D plot so matplotlib does not try to find ideal position](https://github.com/glotaran/pyglotaran-extras/commit/8b6ccbf29812de0547dbc8ae895a64118195510b)
> 🩹 Fix very slow data/residual plots

- .github/workflows/integration-tests.yml
- .github/workflows/test.yml
- requirements_pinned.txt
Combined update PR from dependabot PRs.
- [Bump codecov/codecov-action from 3 to 4](https://github.com/glotaran/pyglotaran-extras/commit/e034b639d2d0bb52672f3dcb550ad262a396619e)
- [Bump pre-commit/action from 3.0.0 to 3.0.1](https://github.com/glotaran/pyglotaran-extras/commit/d0bb1888cf418fbc096b56bd91d492c3e444272f)
- [Bump pypa/gh-action-pypi-publish from 1.8.11 to 1.8.14](https://github.com/glotaran/pyglotaran-extras/commit/1b9abe21935b40725e3d59eb26650522b4092cdc)
- [Bump numpy from 1.26.3 to 1.26.4](https://github.com/glotaran/pyglotaran-extras/commit/b1f468d757cb87ec04abbc52f91b18fe22382d52)
- [Bump matplotlib from 3.8.2 to 3.8.3](https://github.com/glotaran/pyglotaran-extras/commit/e5b01c9e844a7ef4d6eb34183b1d71b6dcaff393)
- [Bump xarray from 2024.1.1 to …
> ⬆️ Combined updates

- .github/workflows/integration-tests.yml
Switch back to `GeekyEggo/delete-artifact` after the permission issue fix was released.
- [🚇🧹 Switch back to GeekyEggo/delete-artifact](https://github.com/glotaran/pyglotaran-extras/commit/e8fd9533ecf2446edd817132d6f0b18fa0e30055)
> 🚇🧹 Switch back to GeekyEggo/delete-artifact

- .github/workflows/test.yml
- codecov.yml
The action [`codecov/codecov-action@v4` removed support for tokenless uploads](https://github.com/codecov/codecov-action/releases/tag/v4.0.0) so `pushes` to `main` failed upload coverage reports for the last 3 months.
However, [uploads from PRs done by forks still work](https://app.codecov.io/github/glotaran/pyglotaran-extras/pulls). so this [issue can only be seen for pushes on main](https://github.com/glotaran/pyglotaran-extras/actions/runs/9418439314)
- [🚇 Add CODECOV_TOKEN](https://github.com/glotaran/pyglotaran-extras/commit/be7234a9d90bac917038be517747757049604850)
> 🚇 Add CODECOV_TOKEN

- pyglotaran_extras/plotting/plot_overview.py
- pyglotaran_extras/plotting/utils.py
This change fixes the deprecation warning:
```py
FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
center_λ = min(res.dims["spectral"], round(res.dims["spectral"] / 2))
```
When `center_λ` has its default value of `None`.
However, when fixing this I found that we have a bug.
First of all:
```py
min(res.sizes["spectral"], round(res.sizes["spectral"] / 2))
```
will always return `round(res.sizes["spectral"] / 2)` since `res.sizes["spectral"]` is the length of the spectral coordinate (same goes for the current and past behavior of `res.dims["spectral"]`)
But since this value is later used with …
> 🩹 Fix deprecation warning for using xr.Dataset.dim

- .github/workflows/integration-tests.yml
This change fixes the [failing CI](https://github.com/glotaran/pyglotaran-extras/actions/runs/9629135960) due to changes in the outputs in the pyglotaran-examples github action.
- [🩹🚇 Adapt to changed outputs in pyglotaran-examples GHA](https://github.com/glotaran/pyglotaran-extras/commit/f80b103e3fe32df1b564d7cbcb61292a539dbe06)
> 🩹🚇 Adapt to changed outputs in pyglotaran-examples GHA

- .github/workflows/integration-tests.yml
- .gitignore
- .pre-commit-config.yaml
- pyglotaran_extras/plotting/plot_pfid.py
- pyglotaran_extras/plotting/plot_spectra.py
- pyglotaran_extras/plotting/utils.py
- tests/plotting/test_utils.py
Module containing PFID (Perturbed Free Induction Decay) plotting functionality
- ✨Added plot_pfid - a plot module to plot data related to modelling PFID (Perturbed Free Induction Decay)
- 🎨 Inverse plot order (zorder) of spectra
- 👌Added `condense_numbered_strings` utility function to condense plot labels (e.g. osc1,osc2 -> osc1-2)
`plot_pfid` with `show_clps=False`
`plot_pfid` with `show_clps=True`
> ✨ Add plot_pfid plot function

- .github/requirements_min.txt
- changelog.md
- pyglotaran_extras/__init__.py
The v0.7.3 release will include support for plotting config and pfid_plot.
* 🚧 Bump version from 0.7.2 to 0.7.3.
* 📚 Updated changelog, added release date.
* ➡️ Set min pyglotaran version to v0.7.0.
> 📚 Prepare for v0.7.3 release

- changelog.md
- pyglotaran_extras/config/plot_config.py
- tests/config/test_plot_config.py
This PR fixes that `find_axes` raises a `TypeError` when a config enabled function (has a `use_plot_config` decorator) has a `xr.DataArray` argument or return value.
Thanks @jsnel for discovering this error.
We didn't catch this error earlier since all our examples use `xr.Dataset` and when iterating over `xr.Dataset` you get the keys of the `data_vars`.
For `xr.DataArray` however `find_axes` recursively looks up sub `xr.DataArray` until it gets to a point where the value is a single item `xr.DataArray` and raises the `TypeError` due to the dimensionality check in its `__iter__`.
In addition to fixing the above described bug, this PR also fixes that `Mappings` of `Axes` as arguments or return values wouldn't have been handled correctly.
**Minimal reproducible example:**
```py
import …
```
> 🩹 Fix find_axes inside use_plot_config  causing TypeError with DataArray
